apiVersion: v1
data:
    password: ENC[AES256_GCM,data:awS+9Fm+nnqQx+yl,iv:RpaMwwXJtK11l6kfC1c8ZtJo4Cnvjw0/P+TjuLc8sWU=,tag:m+H6Kc0Tc7nfPR9lrrfC5Q==,type:str]
    user: ENC[AES256_GCM,data:SGYa+jc7gnw=,iv:e1hoWUtEEmEjrvjdcOh/ixfwu62dSZlbSEpoSTvvZBw=,tag:S6WcCxf/SA0oijFiXe0D+g==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZGlhU0ZLSTZoS3ZWSE5M
            SmZHZ1FzZy9zSlFxZTU5TDE0ZDNNVHdlTlVZCitNZ05MYjlXOWc3WFVVa2lBUFQv
            MUVmL280SS9oOTVkRUdhZHppSkJtbGcKLS0tIHhEQW5GZmJjQjV2R1o3Q0N3YmFk
            dWd3dUZjOEFCQ1BXWUp4cG1IckUxamMKVgyjdJRYhO2P3Iq6Y9kv424efO4A/bt9
            XtWCMjJ/GYQDmC0RrVGhGCO65Apvzt45rxHABNVUBj2vAmJBBbtUmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cstt3vzkqqzz9rhdlc4f3u04wrtky5hpckf0uzvqdhjrjghm3fjssmyh2u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T18:30:51Z"
    mac: ENC[AES256_GCM,data:78UAHjh8qg/txsCu2QWon2m7hrjkkb/YwQUEa0KsflIm/uyt3lV3NdgwlxcCqamD/9xGiFM02wzE4WvWUvUf83jO5o/JAeC/+JrAQabRJ93eQHuQb2vthcPiSgQ/EehEajVknptF5LqZ6yaDl0nvDZcAFmMPwJGEJjWisNrDFwk=,iv:vkjLBjRUmB18bWsVBId3044VpuVxqGRWg+GMkWq1TGA=,tag:KN2Tq9HpFBRozMD+sRaHnA==,type:str]
    version: 3.13.3
