apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  replicas: 1

  selector:
    matchLabels:
      app: wordpress

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: wordpress

    spec:
      containers:
        - name: wordpress
          image: wordpress:7.1.2-php8.3-apache
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              containerPort: 80

          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb:3306
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-database
                  key: password

          readinessProbe:
            httpGet:
              path: /wp-login.php
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /wp-login.php
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20

          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html

      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-data
