apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:rm6+YNzOqHZVR+RmS7BwBxtzFhJHCDWhH4hmIcnQJydD7JFYaACky4o70+lNMY9lsljM5Snujvd3I9h+0lRsUhgeLFF9aqXHp9D7Hvx0qA1EvU7AjmYGlfyOParlerwXcgpOg3TaXtR7873dTZk4NKj6O/7qpT3sdwHJ6lnB3X0+WeI9PfgidfEiuDQJTvvBRfGd+yG5SrzN/uLszOnwKwWMYKNkHQudNkuNHS1dGLIjNTHjTAgZyCpvvtj1HenwKIPD16Bg2IwASTqpbbN6MpvUx5ym+yTnYnk9nRpBwN26fUTk95C3Q2uehTE=,iv:s2c/mNqgbZz3mMmIU23uVVlUtqBrOZ5971DCww7weaw=,tag:XQOlnIMATsr2sYS1+u9Dew==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMXIrVE1PajBsQU8zeHcr
            ci92NktTWEpoT000MkZac2tUZkdBYVNyam53Cm4yczVCcDZGbkJqU2ZaeU02MzlF
            ZStEMmk0Z0ExbDFqcXhJdkF3eU11N1EKLS0tIDZHbGR6Z1BabS9vR1FVWjVJUFdI
            M252WlVEZHppakJDTUp0czhyYlAvMlEKK5v61yU8DA1VZ9cDrWFC+9lsTRsTQhMg
            l3YJbGD/eCCkCeJXmL1/UZKUJ3nSQBU3BLc1jFI/7IRiaEjFTpsXaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cstt3vzkqqzz9rhdlc4f3u04wrtky5hpckf0uzvqdhjrjghm3fjssmyh2u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T18:58:53Z"
    mac: ENC[AES256_GCM,data:VXBqbsL0DXlzdwbW4LeN+XHyu2rM6ZxxCcWPsQHZ09sHWX81OidORX9cJM0kZPEDs04fJw1FEF3xY2cuCzcP37sOS6fGAVZOa3AQFn78rxF01023EesIfWniam3aLDuOlHkZMx6a9aHDVAfm7nd8hZVueomt/ojFTcEPKLHivFU=,iv:fTDIWdImSTMXOALhrJikNwWWnX/1Bsveb47fhkMzsSs=,tag:ps9WwKDl3moJ24MbZvPJVQ==,type:str]
    version: 3.13.3
