apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n
type: Opaque
stringData:
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:yt1d,iv:1xtfxW9Olqn7aKA0hNal7Ag6HJ0Day6K9J+VnrDiywU=,tag:jgWsjz39WxaMawTE8qsOLQ==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:TA2x/5L7rejwyLBf5w==,iv:WiW2XQ2kuzdTFvIVF4r2blhuTEOgde5G4CrTZT67eYk=,tag:DUUriiiC/jqady9mwktTow==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNllLcTZheDZRZzJ4dTNF
        aXZORURsTnhrWTJ6VmpsWjYxOXZUanJqaEZvCkNpSXBwL09kVndMbXNJM3NCY2R5
        WXZWRGhDSzVJUFBrcG5GZS9NZUtKZ0UKLS0tIFFWVXNxdzFuNXk4THBsa1pVTEgr
        QVhWazJyZFAycGhkcld1eDArNGM3ZGsKFrS8CGyEKJDJ2jJ/hz7RyeYH22bcP0Zt
        ZOVHs6HsKKm8mrBRFFKNaH2jptIDtPqNryVuIptzm4WPnXbk0/PGLw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cstt3vzkqqzz9rhdlc4f3u04wrtky5hpckf0uzvqdhjrjghm3fjssmyh2u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T12:43:25Z"
  mac: ENC[AES256_GCM,data:mQ/gKUgbn54yo6xu9LhC7yiLljpL0C66eEOQnDszp+VlteiVcuqM5x1nd806zbHkGpZfmSVaw88vYQJBiJ8DZkQ4P290DgZswv9Ti8D0CKvYkW7ZcPd+GSrlZF3fP6vTLIXLHqF4qczQxJAou2YUpjCLXKuWW2K+Dak6M1De1o8=,iv:opRet3a3wN6f34FeYg4D6jNRRGZOE0QjjvSPPtvz1pU=,tag:dNYzO0ESn0pn8auWHGgZmw==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-db-credentials
  namespace: n8n
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:yt1d,iv:1xtfxW9Olqn7aKA0hNal7Ag6HJ0Day6K9J+VnrDiywU=,tag:jgWsjz39WxaMawTE8qsOLQ==,type:str]
  password: ENC[AES256_GCM,data:TA2x/5L7rejwyLBf5w==,iv:WiW2XQ2kuzdTFvIVF4r2blhuTEOgde5G4CrTZT67eYk=,tag:DUUriiiC/jqady9mwktTow==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNllLcTZheDZRZzJ4dTNF
        aXZORURsTnhrWTJ6VmpsWjYxOXZUanJqaEZvCkNpSXBwL09kVndMbXNJM3NCY2R5
        WXZWRGhDSzVJUFBrcG5GZS9NZUtKZ0UKLS0tIFFWVXNxdzFuNXk4THBsa1pVTEgr
        QVhWazJyZFAycGhkcld1eDArNGM3ZGsKFrS8CGyEKJDJ2jJ/hz7RyeYH22bcP0Zt
        ZOVHs6HsKKm8mrBRFFKNaH2jptIDtPqNryVuIptzm4WPnXbk0/PGLw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cstt3vzkqqzz9rhdlc4f3u04wrtky5hpckf0uzvqdhjrjghm3fjssmyh2u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T12:43:25Z"
  mac: ENC[AES256_GCM,data:mQ/gKUgbn54yo6xu9LhC7yiLljpL0C66eEOQnDszp+VlteiVcuqM5x1nd806zbHkGpZfmSVaw88vYQJBiJ8DZkQ4P290DgZswv9Ti8D0CKvYkW7ZcPd+GSrlZF3fP6vTLIXLHqF4qczQxJAou2YUpjCLXKuWW2K+Dak6M1De1o8=,iv:opRet3a3wN6f34FeYg4D6jNRRGZOE0QjjvSPPtvz1pU=,tag:dNYzO0ESn0pn8auWHGgZmw==,type:str]
  version: 3.13.3
