apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
type: Opaque
data:
    DB_POSTGRESDB_USER: ENC[AES256_GCM,data:Exns,iv:tcRP6Np8MzUJUZOlWWF+oPcY1r8/wanfFlOWC+ywUr8=,tag:FuGYZ5+0NHugRz/v6GjwCQ==,type:str]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:cMwGqk7Z1Cbd/65YYQ==,iv:9+k+NwExjkmyxiuBNOWxkNWMgk0ZGE9AP+6fBOgI2Ts=,tag:ycK+oqRDkLcktBX993w7oA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeldBdnp5RXBYZDVpUzNQ
            dGIwNnFCak93ZCtrY2xvWElsUjVUS3JZdzBzCk5EWi9mWWVGMTM5aFlZSmJiaWhN
            SEpyZm9OcW1sTFlLbzBXY3VvenVOZWMKLS0tIEtSOWgreExSc3VpcDZRbCtjUG5V
            UmRPZ1A5NEVkOHlYRVdhOW5VOHhPSzgKx0fwtrRkbJw0IqJ/wgBXhwM430C/FusY
            XoXYbmzuki/PHJvD0VIw9pHpZ54bmkHyRJC/lJdtlYI7QLFkk2POlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cstt3vzkqqzz9rhdlc4f3u04wrtky5hpckf0uzvqdhjrjghm3fjssmyh2u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T12:28:51Z"
    mac: ENC[AES256_GCM,data:XhP3skzb40MRXQz+2n/4MybZ0GN7peLJlFBtV6UCz98fLpVkQRdk5RqYimHINQ2ugrXhzn9YKf7qbtcIsAIp9KobmlhFwVksVWf/p6/6c6twia4wrX/zepKJD7VzwxkS3bY4YBF94JrclRMOZTmjuVVQWahudsaC40gFcLlvddk=,iv:OaqN1hrGH5gpP+EMxxwATlbHC5o2tBdebM3SwzzrJOA=,tag:+xxNt9FbiY/gEVO99JJ6Kw==,type:str]
    version: 3.13.3
