apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-credentials
    namespace: n8n
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:TfTP,iv:cV+hIFVU9Ms9/2I27H4ZPK/NxSZbaBYqkNhlFrSj1zE=,tag:7TMJ/NwuT9K4mIo1YPJ1bg==,type:str]
    password: ENC[AES256_GCM,data:xd0R0HGW3aEoIxfT1w==,iv:G5ru9v92fgheF55p0+xD6UQnLtSrMr8orMOn6INP7mY=,tag:vER6LZmhk+zQMpGuGKJb/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodzFacEJMNG1GMHJaQ1Bl
            YWZrUU9EVnlhVGl0akNwUmRRUzB6aGNsYlU4ClIvRFl1K3NoWDFwckV0QTU4UkpE
            R1JEeFlFWmZ5VjdteUlxeTNOZEI0V0EKLS0tIDJ2TTF5amoxQW8rT1JlRjJyemFT
            d250Q3psVEZiN0NlUWRtZTgxTlAwWjQKb0kKCWv2HveqKP8J5rSGmEaUUYB0mh3J
            34Tyj7gLZL7Nu5qddpkPRFg+bO0VloW2fO8yUY+Yy3z4hRhqFOSNNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cstt3vzkqqzz9rhdlc4f3u04wrtky5hpckf0uzvqdhjrjghm3fjssmyh2u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T12:59:40Z"
    mac: ENC[AES256_GCM,data:zkvdZwIZGTM5KL/VK+VSFyk6YX70NQPUusGTF7HndxmJTbdDKRRZTmJ9z3LOIk06hqf+QnGqy7lcuMePzsWdPYtBYx5q2dmrYEP3lzbnXEKsQws4dWuQmyPS50jl29MzohlMhLG5ZP2iB614/VGwJQ/1RsiRy4Q/LF3s0Et/zGc=,iv:NlzGozUBv+OdZJT0WqIEeaRsKJhszjFH/ICFvEp3W7I=,tag:IQ21p7D5RNlHd+M3mfZcrQ==,type:str]
    version: 3.13.3
