apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
type: Opaque
stringData:
    DB_POSTGRESDB_USER: ENC[AES256_GCM,data:dye+,iv:RqSxeFb2DhlTQuZxUsxtq+wcmBCt3l/BAIa4ywLAv6s=,tag:ICt/D/y5LfcpT6Nsdxg9hw==,type:str]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:N51BHgm+EFPsAs1DAQ==,iv:qdv6fNIFjw9GMmiwpq7Id/U7SI8udCy3z01MoIRr3cE=,tag:K8SHrUHxJKJIHIZjYHnxyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSmZPeDI3c1JLYXlUUU04
            cHpSUXpzWEJsWldqVEdDaWRwNHI5Qm5HTmhrCmt1UzdTTlo4aFBCTnI4Q0Q5UWFC
            WklSay9BcnFzc3JhZStXMHBBNWJPOVkKLS0tIDdWaG9qTHBQcWtjTmN6ZXVWT3NM
            OUdnZ1FtbWl6TzVjdVVCV1ZWWHU3MmMKoqGz7pVz1IvyaXqPC9QAkuq7x3VlFymk
            T7g7rbCnvghvvjrKXrh6usoJC7Xdw/ld4qvfNXLFcHPOQgn5GETTCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cstt3vzkqqzz9rhdlc4f3u04wrtky5hpckf0uzvqdhjrjghm3fjssmyh2u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T12:59:40Z"
    mac: ENC[AES256_GCM,data:bhtrRu6TlfIDpskODw9Lij234YsMvqt231sqHmuOueCA6E1n7xHZl5/cms3pMKbCyb1P5PGhKCN+EVjX0TgXiGqVl5Xgfvnia26LElFPmhddwKsjJ+zjPoNUH2qBeUVUwbU/9DrM43WamE1JPT+SW9HjDfzqiljb/F8Zpf76umU=,iv:ZTN8MrO9PbFdDV7F72WLt5F9Qc6yaZAfpCoQQBsIQDo=,tag:UfdHQqC1vANoPUgCMiZZyA==,type:str]
    version: 3.13.3
