apiVersion: v1
kind: Secret
metadata:
    name: wordpress-database
    namespace: wordpress
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:LcBo6RNf1cxKzTaSA1VXrkm4fEu6R8I4m7HpAB9HlsHuRFqHdmHbk/QDn/8TNqei,iv:StkIpUxdqqLX049hRfL0PWOkpwOf7LscI4Gk2a20iEk=,tag:nH2jrIa7A3Py/aElW1mF5w==,type:str]
    root-password: ENC[AES256_GCM,data:KZatErInPT2aUU0Ii6gWRqpyiggddD+1k3zsoYBTXloHHEXoLDyBfIyWSmXGSC7HqFbvsQ==,iv:RlrnO5qWTeLIOHBCm7pOZXM0YFqC9FGn1crMTVAaP1c=,tag:EEvyjS+BcoG4oZYW6bkqAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMjFEam9PTkhZN1BhdlVF
            ekEvbkgva1ROVDg4dWVVZmoyM20xalNhL3owCmROOWo5eUt1Y295Qnh5Rmh3blhy
            WjErcFdTTkp1NFhyV1ZSRDc3TTlPMWcKLS0tIGFsTUw4aUlnWkdRckRkd2M5SWVj
            cFQwRlFGRmwxMG1sNnlsRUluWGR3TlkKj3WEYPQI269A4LnCr44ISTRmnEOa2i0i
            dlxCz6G+A8a41s39lftLtlG0qMV96c/gLWlPnk8odYnq30YSoX66cA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cstt3vzkqqzz9rhdlc4f3u04wrtky5hpckf0uzvqdhjrjghm3fjssmyh2u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T23:48:12Z"
    mac: ENC[AES256_GCM,data:7N0fREgYi1cix7AyRVo5oOAArkJ5+axHL0zCcP4VeUJ3Zg7r5M21Rfg2gEMILqC9EbDNMt4X12wa88oQnzwlXPxUJt3UQU0iaccQE5gEF2hUiKrZHSCoDJuLL3nEjWMKiPFWKJyfdhs3ndPPnEmbZ+ZVugKQ7tE7ZGdHpeP0xU8=,iv:V40BYKUnHPpLJzzlCn3i0dc9ioSAMPjxz+JWSa65om4=,tag:zZW1+mlvO6EH7oE0v2/w7Q==,type:str]
    version: 3.13.3
