apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ziJAXKE5bHzIv+DEqBYTsObA4T08D+kh8Espu7ZZhKUxxlxavWoDpu8JFpgpfPu3AMZkBnQXAKzybuesKKdkNq4ywnkuRAr0lmeRGUx3C3ThP+IqCxIFQIFhDaQa+f6zFxpPj+HtYmOW9Bv6l4JPL4D84KtMxieda60CChlkkCqtVqlVtLE4HlJSuVarYkIwLreuVIvX6bfYTc9SUCReBIkpVu7Pzla9ufLbhS6hVzR5vS0DFwdtEvZj9AmJtWX+LFyYDe8jzFCnQ9MFdiWIf74hAvOLzBFBWsOkHrc1SfXF61cEM2UtvtstzR4=,iv:BDDIJcaz1nf4NdaWZsBtPFbVbVh1reROIIdLM8aCpAY=,tag:kKUiGW03C92QXbWnMtRttg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: wordpress
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYkZTYUFPdzBUMXoxQjkr
            d2NaNVpQanZtbnNoVWJFa3ZzbXZrZTZHejE0CkYxNGhpNkFDOElWVXV6WnQ5UjQy
            dTNLTDFjb3FnT3luUmduNGxWUGo2OVUKLS0tIGozV292ZkM1MklDRzJVQUVZWHhy
            SHFXQmFWVW8venNkUjdiVG5WN3A0eXcK6X6jR/I2aBdYsfpYolQkVMpjB9FCllbw
            F7vDqpLmyqweMHV6tBu/XLebKAKfEIwkA/z8FoMHJwCq8sgl7FufDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cstt3vzkqqzz9rhdlc4f3u04wrtky5hpckf0uzvqdhjrjghm3fjssmyh2u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T14:11:01Z"
    mac: ENC[AES256_GCM,data:Lqf1dyXGfpXfYyj5zxKlJAfDYOfbelAemm52XeezOTTR5QkavZTZNaQRmLJ1byfwTyXN3xsWtdkmUHHd5CriUQhSFd8b4bsax7q9go4H+RQDOSCz6TcMXmtKaQfDFaPYdHzaKuOjvihOPr87+PqZA1WT+NUYk64sCxYBqbwMuBQ=,iv:zAOE1UPJxv1QSE2bAulSf599/NBNCKlAayC5jsfAaow=,tag:2t+nsjLTkwJbyu2T31Tdcw==,type:str]
    version: 3.13.3
