apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:bfpzSfo7FPEHWx+85+pqIxuHoUwEOSPHhbk7uq+0PXZvrUtLnPtkFwt94VKIn8RTJ09tU5cIrfU=,iv:dwh9gg4gpXj2974f5+MzRMJro8GEeyW9X/V+5ktI4Zg=,tag:tfd2iDvmkRtbONw8HZVnVw==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dVR5Q1k4Z3lkREkvY1V2
            emtQUmR1YVplYXRqcldqd2VJWDBZblhLU1NRCnZHQkJuVXJ3YlB6dkROMHNWd1V5
            VUczblo5QUY3dWxvUUxlYVpTQXoxM2sKLS0tIFVjcktsOXN6ZnRKMUFwM200Lzkw
            OWM0bTBqZ1JRc1lBS0JpcWR1TUlYNEkKQ/YyvlISUJ6iUyngtJeWgFAYpwdRFJBH
            WSuPQhj7Wjg0cMmzckWQiEFA+L6eEUE1fwUBm43HFEKIhWnJfjGPVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cstt3vzkqqzz9rhdlc4f3u04wrtky5hpckf0uzvqdhjrjghm3fjssmyh2u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T13:30:50Z"
    mac: ENC[AES256_GCM,data:KbrgzuByTYQTaCYS9Sym7sD+EwbCcybgccUXBmfbg5j7BrXMKbOgs/36v48f5zLR7+4st+dAd5cWQZRIiPrAkyv4Q3MbAl5mSL932mxVsybrMZcErXPNDBcuKdh/MYLGWBP5S2BlsWx3ft7NA2FsTx3+RjeGrcmX5dUc7VJuMmY=,iv:gNTg555etkLuJQSvAxcD1LWPMECZxYLAjuEfjSt2gVs=,tag:OlZwAArhZwWvUz5mW6rOnQ==,type:str]
    version: 3.13.3
